### ISSUE TITLE
Error: spawn chrome ENOENT

### ISSUE THREAD

**Issue by superfein** [amoser67/shopify_dev_utils#2]
Node v13+
Windows 10

Error: spawn chrome ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn chrome',
  path: 'chrome',
  spawnargs: [ 'http://localhost:8080' ],
  cmd: 'chrome http://localhost:8080'
}

I tried commenting out data.port in run.js, but got the same error except that http://localhost:8080 was http://localhost:undefined.

**Comment by amoser67** [comment]
Alright, I think I fixed it, go ahead and grab the latest version and see if it's resolved.  Btw this error would have been affecting all Windows users, so definitely my bad on that one.

**Comment by superfein** [comment]
@amoser67 I'm just so excited that you've created this, that I don't mind at all helping to improve it. Unfortunately still getting a similar error message after updating to 1.0.19:

`Error: spawn start ENOENT`
>   at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn start',
  path: 'start',
  spawnargs: [ 'http://localhost:8080' ],
  cmd: 'start http://localhost:8080' 
}

**Comment by superfein** [comment]
Not sure if this is useful, but I came across this and thought it may be: https://github.com/sindresorhus/open
OR
https://github.com/domenic/opener

Info came from here: https://stackoverflow.com/questions/8500326/how-to-use-nodejs-to-open-default-browser-and-navigate-to-a-specific-url

**Comment by amoser67** [comment]
I figured out what the issue was.  Version 1.0.20 should work for you (tested the changes in windows).

Reason (if you are interested):
Node has a module called child_process which I use to call executable files from the JS, as if I were doing it in the terminal.  On windows, you have a command "start", and on unix systems, this would imply there is some binary file in one of the bin directories which is called "start".

What I think happened was that using child_process.execFile("start", [url], ... caused an error due to the fact that binaries on windows have to have the .exe extension.  I ended up using:
child_process.exec('start url', ... And this worked when I tested it on windows.  Using the old method threw the error you sent.  I think the old method could also be changed to execFile("start.exe", [url]  but I stopped testing after I found a solution so I can't say for sure.

**Comment by superfein** [comment]
Thanks @amoser67, that definitely fixed the issue. Now getting a completely different error message:

`[12:15:54] - The following exception was triggered:  startcreate_websocketReferenceError: command is not defined`

At this point in the CLI it just hangs permanently. I tried in a few different CLIs, like Git Bash, cmd and Powershell. Exact same error across all three.

**Comment by amoser67** [comment]
Oops, forgot to copy a variable name change when I published the last version, indeed command was not defined lol

**Comment by superfein** [comment]
Works! Thanks @amoser67 you're a champ!

I'm still not entirely sure how to use the app. Here's what I tried to do but it failed.

In the styles folder in the root I've created a file `theme.scss` and I'm importing several partials into this file from `styles/components/name-of-partial.scss`. When I use this structure I get this error in the console: 
`Error: File to read not found or unreadable: C:/Users/zach/Shopify Sites/dev-utils/styles/main.scss
    at options.error (C:\Users\zach\Shopify Sites\dev-utils\node_modules\node-sass\lib\index.js:291:26) {
  status: 3,
  message: 'File to read not found or unreadable: C:/Users/zach/Shopify Sites/dev-utils/styles/main.scss',
  formatted: 'Internal Error: File to read not found or unreadable: C:/Users/zach/Shopify Sites/dev-utils/styles/main.scss\n'
}`  

I was hoping to be able to use this structure and of course SASS for development.

Forgot to mention: the Shopify dev store has the password enabled. When I "node run" the proxy works and opens localhost:8080 with https (which is fantastic!) in Chrome. But even when I input the store's password the password page is never disabled/deactivated. So my only option seems to be to disable the store password. Did you get this same behavior?

Thanks again for updating the app for me. You're a gem!

**Comment by amoser67** [comment]
Sounds like you are doing everything right with your styles setup, I'll look into it.

For the password thing I will have to do some testing.  I think the main problem is that the request to the shopify store doesn't save cookies, so I will either have to see if I can save the cookies locally or see if there is any way around the issue in Shopify.

For a temporary solution, you could always just unpublish your theme (make it not the active one) and then use the optional .env variable: store_preview_url.  Not sure how much detail is given in the README, but basically you preview the non active theme and then click the share preview link or whatever, copy the link, then add that as an additional .env variable.

**Comment by amoser67** [comment]
Oh, try renaming it main.scss (instead of theme), think that is something I will have to add another .env variable for, so that people can name it what they want.

**Comment by superfein** [comment]
I can't believe I missed that! In your docs it's clear the file is named main.scss. I renamed it and it worked, created a file named main.min.scss.liquid in the /assets folder. 

Unfortunately, right after creating the file in the /assets folder the app fails and I get this error:

`C:\Users\zach\Shopify Sites\dev-utils\node_modules\shopify_dev_utils\requestor_factories\api_requests.js:392
                if (err) throw err;`
                         ^

`[Error: ENOENT: no such file or directory, open 'C:\Users\zach\Shopify Sites\dev-utils\theme\undefined\C:\Users\zach\Shopify Sites\dev-utils\theme\assets\main.min.css.liquid'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\zach\\Shopify Sites\\dev-utils\\theme\\undefined\\C:\\Users\\zach\\Shopify Sites\\dev-utils\\theme\\assets\\main.min.css.liquid'
}`

I followed your instructions and I am using the store_preview_url with the unpublished theme. Seems to work. I haven't really been able to test the hot reload feature since the app fails too quickly, but once I "node run" the website loads automatically in my default browser with the URL localhost:8080. It's not https as I had initially thought, but neither Shopify nor Chrome are giving me issues with not loading files so I guess the SSL cert doesn't matter. I've tried other Shopify dev workflows where the lack of a self-signed SSL created some issues locally.

**Comment by amoser67** [comment]
I think its due to the differences between unix and windows paths, I will hop on windows and figure it out.

Regarding the requests, each one is an https request.  A local node server is created which acts as a proxy between the browser and the Shopify servers.  Basically, when the browser submits a request to localhost:8080, our local server receives that request, makes a secure request to shopify, then sends Shopify's response as the response to the original localhost:8080 request.

**Comment by amoser67** [comment]
Alright, sorry for the delay man, been busy with work.  I added support for Windows paths in the latest version.
